### ISSUE TITLE
ImportError: cannot import name 'Deque'

### ISSUE THREAD

**Issue by KingTamo** [x4nth055/pythoncode-tutorials#38]
Hello
When I tried the .py like that python demo.py https://github.com -m 1 , I encountered this Traceback errors
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from requests_html import HTMLSession
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\requests_html.py", line 9, in <module>
    import pyppeteer
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\__init__.py", line 30, in <module>
    from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\launcher.py", line 24, in <module>
    from pyppeteer.browser import Browser
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\browser.py", line 13, in <module>
    from pyppeteer.connection import Connection
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\pyppeteer\connection.py", line 12, in <module>
    import websockets
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .auth import *
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\auth.py", line 15, in <module>
    from .server import HTTPResponse, WebSocketServerProtocol
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\server.py", line 49, in <module>
    from .protocol import WebSocketCommonProtocol
  File "C:\Users\Future\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 18, in <module>
    from typing import (
ImportError: cannot import name 'Deque'

Any ideas?

**Comment by x4nth055** [comment]
Hey there,

I think you have an older Python version, please get Python 3.6.1+ and please let me know if it persists.

Thanks,
Rockikz.
