### ISSUE TITLE
The Youtube comment scraper seems to be down.

### ISSUE THREAD

**Issue by Hypurl** [x4nth055/pythoncode-tutorials#49]
Getting error:
`runfile('C:/Users/Jeff/Downloads/untitled1.py', wdir='C:/Users/Jeff/Downloads')
Traceback (most recent call last):

  File "C:\Users\Jeff\Downloads\untitled1.py", line 120, in <module>
    for count, comment in enumerate(get_comments(url)):

  File "C:\Users\Jeff\Downloads\untitled1.py", line 50, in get_comments
    data = json.loads(data_str)

  File "C:\Users\Jeff\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)

  File "C:\Users\Jeff\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\Jeff\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value`

**Comment by sarahelizabeth** [comment]
It's not working for me either. I'm getting the same JSONDecodeError/Traceback that you are.

**Comment by x4nth055** [comment]
I'm having the same issue too, while I'll try to fix the code, please refer to YouTube API tutorial instead (and that's what I'm currently using as well):
https://www.thepythoncode.com/article/using-youtube-api-in-python
Hope this helps!
